// This file was auto-generated by Fern from our API Definition.

import type * as TransxactApi from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { Payout } from "../../../types/Payout.js";

export const ListPayoutsResponse: core.serialization.ObjectSchema<
    serializers.ListPayoutsResponse.Raw,
    TransxactApi.ListPayoutsResponse
> = core.serialization.object({
    data: core.serialization.list(Payout),
    hasMore: core.serialization.boolean(),
});

export declare namespace ListPayoutsResponse {
    export interface Raw {
        data: Payout.Raw[];
        hasMore: boolean;
    }
}
