// This file was auto-generated by Fern from our API Definition.

/** Always FJD in v1. */
export const CheckoutSessionCurrency = {
    Fjd: "FJD",
} as const;
export type CheckoutSessionCurrency = (typeof CheckoutSessionCurrency)[keyof typeof CheckoutSessionCurrency];
