// This file was auto-generated by Fern from our API Definition.

/** `test` for a session made with an `sk_test_` key, `live` for an `sk_live_` key. Webhook endpoints each hear one mode, and the payload says which it came from. */
export const CheckoutSessionMode = {
    Test: "test",
    Live: "live",
} as const;
export type CheckoutSessionMode = (typeof CheckoutSessionMode)[keyof typeof CheckoutSessionMode];
