// This file was auto-generated by Fern from our API Definition.

/** `pending` until the Customer pays or the session ends. `succeeded`: paid, safe to fulfil. `failed`: the payment was declined or didn't go through. `cancelled`: you cancelled it or it expired unpaid. Only `pending` ever changes, and each change sends the matching `checkout_session.*` webhook. */
export const CheckoutSessionStatus = {
    Pending: "pending",
    Succeeded: "succeeded",
    Failed: "failed",
    Cancelled: "cancelled",
} as const;
export type CheckoutSessionStatus = (typeof CheckoutSessionStatus)[keyof typeof CheckoutSessionStatus];
