// This file was auto-generated by Fern from our API Definition.

export interface CheckoutSession {
    /** Checkout Session identifier. */
    id: string;
    /** Current status of the Checkout Session. */
    status: CheckoutSession.Status;
    /** Amount to charge, in FJD cents (minor units). */
    amount: number;
    /** Always FJD in v1. */
    currency: CheckoutSession.Currency;
    /** Transxact-hosted URL to redirect the Customer to. */
    hostedUrl: string;
}

export namespace CheckoutSession {
    /** Current status of the Checkout Session. */
    export const Status = {
        Pending: "pending",
        Succeeded: "succeeded",
        Failed: "failed",
        Cancelled: "cancelled",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    /** Always FJD in v1. */
    export const Currency = {
        Fjd: "FJD",
    } as const;
    export type Currency = (typeof Currency)[keyof typeof Currency];
}
