// This file was auto-generated by Fern from our API Definition.

export interface Error_ {
    error: Error_.Error_;
}

export namespace Error_ {
    export interface Error_ {
        /** Stable machine-readable error code. */
        code: string;
        /** Human-readable detail, not contractual. */
        message: string;
    }
}
