// This file was auto-generated by Fern from our API Definition.

/**
 * Branch on `code`; `message` is for logs.
 */
export interface ErrorError {
    /** Stable machine-readable error code. */
    code: string;
    /** Human-readable detail, not contractual. */
    message: string;
}
