// This file was auto-generated by Fern from our API Definition.

import type * as TransxactApi from "../index.js";

export interface Error_ {
    /** Branch on `code`; `message` is for logs. */
    error: TransxactApi.ErrorError;
}
