// This file was auto-generated by Fern from our API Definition.

import type * as TransxactApi from "../index.js";

export interface GetV1PayoutsResponse {
    data: TransxactApi.Payout[];
    hasMore: boolean;
}
