// This file was auto-generated by Fern from our API Definition.

/** Mode of the API key used for this request. */
export const MerchantMode = {
    Test: "test",
    Live: "live",
} as const;
export type MerchantMode = (typeof MerchantMode)[keyof typeof MerchantMode];
