// This file was auto-generated by Fern from our API Definition.

import type * as TransxactApi from "../index.js";

export interface Merchant {
    /** Merchant's account tier. */
    tier: TransxactApi.MerchantTier;
    /** Mode of the API key used for this request. */
    mode: TransxactApi.MerchantMode;
    /** Earned balance not yet swept into a Payout, in FJD cents (minor units). */
    balance: number;
    /** When Payouts are made, in UTC: `daily`; `weekly` on Mondays (the default); `fortnightly` on every other Monday; `monthly` on the 1st; or `manual`, where a Payout is made only when the Merchant asks for one from the dashboard. Set on the dashboard. */
    payoutSchedule: TransxactApi.MerchantPayoutSchedule;
}
