// This file was auto-generated by Fern from our API Definition.

/** When Payouts are made, in UTC: `daily`; `weekly` on Mondays (the default); `fortnightly` on every other Monday; `monthly` on the 1st; or `manual`, where a Payout is made only when the Merchant asks for one from the dashboard. Set on the dashboard. */
export const MerchantPayoutSchedule = {
    Daily: "daily",
    Weekly: "weekly",
    Fortnightly: "fortnightly",
    Monthly: "monthly",
    Manual: "manual",
} as const;
export type MerchantPayoutSchedule = (typeof MerchantPayoutSchedule)[keyof typeof MerchantPayoutSchedule];
