// This file was auto-generated by Fern from our API Definition.

export interface Merchant {
    /** Merchant's account tier. */
    tier: Merchant.Tier;
    /** Mode of the API key used for this request. */
    mode: Merchant.Mode;
    /** Earned balance not yet swept into a Payout, in FJD cents (minor units). */
    balance: number;
}

export namespace Merchant {
    /** Merchant's account tier. */
    export const Tier = {
        Business: "business",
        Individual: "individual",
    } as const;
    export type Tier = (typeof Tier)[keyof typeof Tier];
    /** Mode of the API key used for this request. */
    export const Mode = {
        Test: "test",
        Live: "live",
    } as const;
    export type Mode = (typeof Mode)[keyof typeof Mode];
}
