// This file was auto-generated by Fern from our API Definition.

export interface Merchant {
    /** Merchant's account tier. */
    tier: Merchant.Tier;
    /** Mode of the API key used for this request. */
    mode: Merchant.Mode;
    /** Earned balance not yet swept into a Payout, in FJD cents (minor units). */
    balance: number;
    /** When Payouts are made, in UTC: `daily`; `weekly` on Mondays (the default); `fortnightly` on every other Monday; `monthly` on the 1st; or `manual`, where a Payout is made only when the Merchant asks for one from the dashboard. Set on the dashboard. */
    payoutSchedule: Merchant.PayoutSchedule;
}

export namespace Merchant {
    /** Merchant's account tier. */
    export const Tier = {
        Business: "business",
        Individual: "individual",
    } as const;
    export type Tier = (typeof Tier)[keyof typeof Tier];
    /** Mode of the API key used for this request. */
    export const Mode = {
        Test: "test",
        Live: "live",
    } as const;
    export type Mode = (typeof Mode)[keyof typeof Mode];
    /** When Payouts are made, in UTC: `daily`; `weekly` on Mondays (the default); `fortnightly` on every other Monday; `monthly` on the 1st; or `manual`, where a Payout is made only when the Merchant asks for one from the dashboard. Set on the dashboard. */
    export const PayoutSchedule = {
        Daily: "daily",
        Weekly: "weekly",
        Fortnightly: "fortnightly",
        Monthly: "monthly",
        Manual: "manual",
    } as const;
    export type PayoutSchedule = (typeof PayoutSchedule)[keyof typeof PayoutSchedule];
}
