// This file was auto-generated by Fern from our API Definition.

/** Merchant's account tier. */
export const MerchantTier = {
    Business: "business",
    Individual: "individual",
} as const;
export type MerchantTier = (typeof MerchantTier)[keyof typeof MerchantTier];
