// This file was auto-generated by Fern from our API Definition.

export interface Payout {
    /** Payout identifier. */
    id: string;
    /** Amount paid out, in FJD cents (minor units). */
    amount: number;
    /** Business -> bank_transfer, Individual -> wallet. */
    rail: Payout.Rail;
    /** Unix ms timestamp of the settlement run that created this Payout. */
    createdAt: number;
}

export namespace Payout {
    /** Business -> bank_transfer, Individual -> wallet. */
    export const Rail = {
        BankTransfer: "bank_transfer",
        Wallet: "wallet",
    } as const;
    export type Rail = (typeof Rail)[keyof typeof Rail];
}
