// This file was auto-generated by Fern from our API Definition.

/** pending until the money reaches your payout destination, then paid. failed means the transfer didn't go through; the amount returns to your balance and goes out in the next Payout. Test mode Payouts are always paid. */
export const PayoutStatus = {
    Pending: "pending",
    Paid: "paid",
    Failed: "failed",
} as const;
export type PayoutStatus = (typeof PayoutStatus)[keyof typeof PayoutStatus];
