// This file was auto-generated by Fern from our API Definition.

/** Business -> bank_transfer, Individual -> wallet. */
export const PayoutRail = {
    BankTransfer: "bank_transfer",
    Wallet: "wallet",
} as const;
export type PayoutRail = (typeof PayoutRail)[keyof typeof PayoutRail];
