// This file was auto-generated by Fern from our API Definition.

import type * as TransxactApi from "../index.js";

export interface Payout {
    /** Payout identifier. */
    id: string;
    /** Amount paid out, in FJD cents (minor units). */
    amount: number;
    /** Business -> bank_transfer, Individual -> wallet. */
    rail: TransxactApi.PayoutRail;
    /** pending until the money reaches your payout destination, then paid. failed means the transfer didn't go through; the amount returns to your balance and goes out in the next Payout. Test mode Payouts are always paid. */
    status: TransxactApi.PayoutStatus;
    /** Unix ms timestamp the Payout was paid, or null. */
    paidAt: number | null;
    /** Why the transfer failed, when status is failed. */
    failureReason: string | null;
    /** Unix ms timestamp of the settlement run that created this Payout. */
    createdAt: number;
}
