// This file was auto-generated by Fern from our API Definition.

import type * as TransxactApi from "../../../index.js";

export interface ListPayoutsResponse {
    /** This page of Payouts. */
    data: TransxactApi.Payout[];
    /** True if more Payouts follow; pass the last id as `starting_after` to get them. */
    hasMore: boolean;
}
