// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "idempotency-key": "a1b2c3d4-order-9912",
 *         amount: 5000,
 *         currency: "FJD"
 *     }
 */
export interface CreateCheckoutSessionRequest {
    /** Client-generated key; a repeated key returns the original session. */
    "idempotency-key": string;
    /** Amount to charge, in FJD cents (minor units). */
    amount: number;
    /** Always FJD in v1. */
    currency: CreateCheckoutSessionRequest.Currency;
}

export namespace CreateCheckoutSessionRequest {
    /** Always FJD in v1. */
    export const Currency = {
        Fjd: "FJD",
    } as const;
    export type Currency = (typeof Currency)[keyof typeof Currency];
}
