// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "idempotency-key": "a1b2c3d4-order-9912",
 *         amount: 5000,
 *         currency: "FJD"
 *     }
 */
export interface CreateCheckoutSessionRequest {
    /** Client-generated key; a repeated key returns the original session. */
    "idempotency-key": string;
    /** Amount to charge, in FJD cents (minor units). Must be under FJD 5,000.00 (at most 499999), in Test mode and Live mode alike. */
    amount: number;
    /** Always FJD in v1. */
    currency: CreateCheckoutSessionRequest.Currency;
    /** Where the hosted checkout sends the Customer after the payment succeeds. HTTPS only. Transxact appends `session_id=<Checkout Session id>`; confirm the outcome with GET /v1/checkout-sessions/{id} rather than trusting the redirect. */
    successUrl?: string;
    /** Where the hosted checkout sends the Customer if they cancel or the payment doesn't go through. HTTPS only. Transxact appends `session_id=<Checkout Session id>`; confirm the outcome with GET /v1/checkout-sessions/{id} rather than trusting the redirect. */
    cancelUrl?: string;
    /** Up to 20 string key/value pairs (keys ≤40 chars, values ≤500) for matching the session to your own records. Returned on retrieve and in webhooks; never shown to the Customer. Don't put secrets or personal data here. */
    metadata?: Record<string, string>;
    /** Unix ms timestamp, 30 minutes to 24 hours from now, after which the session can't be paid and is cancelled. Defaults to 24 hours. */
    expiresAt?: number;
}

export namespace CreateCheckoutSessionRequest {
    /** Always FJD in v1. */
    export const Currency = {
        Fjd: "FJD",
    } as const;
    export type Currency = (typeof Currency)[keyof typeof Currency];
}
