// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         starting_after: "po_3f9c2b1a",
 *         limit: "10"
 *     }
 */
export interface GetV1PayoutsRequest {
    /** Cursor: return Payouts after this id. */
    starting_after?: string;
    /** Max rows to return (default 10, max 100). */
    limit?: string;
}
