// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "cs_3f9c2b1a"
 *     }
 */
export interface GetV1CheckoutSessionsIdRequest {
    /** Checkout Session identifier. */
    id: string;
}
