// This file was auto-generated by Fern from our API Definition.

import type * as TransxactApi from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const CheckoutSessionCurrency: core.serialization.Schema<
    serializers.CheckoutSessionCurrency.Raw,
    TransxactApi.CheckoutSessionCurrency
> = core.serialization.enum_(["FJD"]);

export declare namespace CheckoutSessionCurrency {
    export type Raw = "FJD";
}
