// This file was auto-generated by Fern from our API Definition.

import type * as TransxactApi from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const CheckoutSessionStatus: core.serialization.Schema<
    serializers.CheckoutSessionStatus.Raw,
    TransxactApi.CheckoutSessionStatus
> = core.serialization.enum_(["pending", "succeeded", "failed", "cancelled"]);

export declare namespace CheckoutSessionStatus {
    export type Raw = "pending" | "succeeded" | "failed" | "cancelled";
}
