// This file was auto-generated by Fern from our API Definition.

import type * as TransxactApi from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CheckoutSessionCurrency } from "./CheckoutSessionCurrency.js";
import { CheckoutSessionStatus } from "./CheckoutSessionStatus.js";

export const CheckoutSession: core.serialization.ObjectSchema<
    serializers.CheckoutSession.Raw,
    TransxactApi.CheckoutSession
> = core.serialization.object({
    id: core.serialization.string(),
    status: CheckoutSessionStatus,
    amount: core.serialization.number(),
    currency: CheckoutSessionCurrency,
    hostedUrl: core.serialization.string(),
    metadata: core.serialization.record(core.serialization.string(), core.serialization.string()),
    expiresAt: core.serialization.number(),
});

export declare namespace CheckoutSession {
    export interface Raw {
        id: string;
        status: CheckoutSessionStatus.Raw;
        amount: number;
        currency: CheckoutSessionCurrency.Raw;
        hostedUrl: string;
        metadata: Record<string, string>;
        expiresAt: number;
    }
}
