// This file was auto-generated by Fern from our API Definition.

import type * as TransxactApi from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ErrorError: core.serialization.ObjectSchema<serializers.ErrorError.Raw, TransxactApi.ErrorError> =
    core.serialization.object({
        code: core.serialization.string(),
        message: core.serialization.string(),
    });

export declare namespace ErrorError {
    export interface Raw {
        code: string;
        message: string;
    }
}
