// This file was auto-generated by Fern from our API Definition.

import type * as TransxactApi from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ErrorError } from "./ErrorError.js";

export const Error_: core.serialization.ObjectSchema<serializers.Error_.Raw, TransxactApi.Error_> =
    core.serialization.object({
        error: ErrorError,
    });

export declare namespace Error_ {
    export interface Raw {
        error: ErrorError.Raw;
    }
}
