// This file was auto-generated by Fern from our API Definition.

import type * as TransxactApi from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const MerchantPayoutSchedule: core.serialization.Schema<
    serializers.MerchantPayoutSchedule.Raw,
    TransxactApi.MerchantPayoutSchedule
> = core.serialization.enum_(["daily", "weekly", "fortnightly", "monthly", "manual"]);

export declare namespace MerchantPayoutSchedule {
    export type Raw = "daily" | "weekly" | "fortnightly" | "monthly" | "manual";
}
