// This file was auto-generated by Fern from our API Definition.

import type * as TransxactApi from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { MerchantMode } from "./MerchantMode.js";
import { MerchantPayoutSchedule } from "./MerchantPayoutSchedule.js";
import { MerchantTier } from "./MerchantTier.js";

export const Merchant: core.serialization.ObjectSchema<serializers.Merchant.Raw, TransxactApi.Merchant> =
    core.serialization.object({
        tier: MerchantTier,
        mode: MerchantMode,
        balance: core.serialization.number(),
        payoutSchedule: MerchantPayoutSchedule,
    });

export declare namespace Merchant {
    export interface Raw {
        tier: MerchantTier.Raw;
        mode: MerchantMode.Raw;
        balance: number;
        payoutSchedule: MerchantPayoutSchedule.Raw;
    }
}
