// This file was auto-generated by Fern from our API Definition.

import type * as TransxactApi from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const MerchantMode: core.serialization.Schema<serializers.MerchantMode.Raw, TransxactApi.MerchantMode> =
    core.serialization.enum_(["test", "live"]);

export declare namespace MerchantMode {
    export type Raw = "test" | "live";
}
