// This file was auto-generated by Fern from our API Definition.

import type * as TransxactApi from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const PayoutStatus: core.serialization.Schema<serializers.PayoutStatus.Raw, TransxactApi.PayoutStatus> =
    core.serialization.enum_(["pending", "paid", "failed"]);

export declare namespace PayoutStatus {
    export type Raw = "pending" | "paid" | "failed";
}
