// This file was auto-generated by Fern from our API Definition.

import type * as TransxactApi from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { PayoutRail } from "./PayoutRail.js";
import { PayoutStatus } from "./PayoutStatus.js";

export const Payout: core.serialization.ObjectSchema<serializers.Payout.Raw, TransxactApi.Payout> =
    core.serialization.object({
        id: core.serialization.string(),
        amount: core.serialization.number(),
        rail: PayoutRail,
        status: PayoutStatus,
        paidAt: core.serialization.number().nullable(),
        failureReason: core.serialization.string().nullable(),
        createdAt: core.serialization.number(),
    });

export declare namespace Payout {
    export interface Raw {
        id: string;
        amount: number;
        rail: PayoutRail.Raw;
        status: PayoutStatus.Raw;
        paidAt?: number | null;
        failureReason?: string | null;
        createdAt: number;
    }
}
