// This file was auto-generated by Fern from our API Definition.

import type * as TransxactApi from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const PayoutRail: core.serialization.Schema<serializers.PayoutRail.Raw, TransxactApi.PayoutRail> =
    core.serialization.enum_(["bank_transfer", "wallet"]);

export declare namespace PayoutRail {
    export type Raw = "bank_transfer" | "wallet";
}
