// This file was auto-generated by Fern from our API Definition.

import type * as TransxactApi from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const CreateCheckoutSessionRequestCurrency: core.serialization.Schema<
    serializers.CreateCheckoutSessionRequestCurrency.Raw,
    TransxactApi.CreateCheckoutSessionRequestCurrency
> = core.serialization.enum_(["FJD"]);

export declare namespace CreateCheckoutSessionRequestCurrency {
    export type Raw = "FJD";
}
