// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         startingAfter: "po_3f9c2b1a",
 *         limit: "10"
 *     }
 */
export interface ListPayoutsRequest {
    /** Cursor: return Payouts after this id. */
    startingAfter?: string;
    /** Max rows to return (default 10, max 100). */
    limit?: string;
}
