// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "po_3f9c2b1a"
 *     }
 */
export interface RetrievePayoutsRequest {
    /** Payout identifier. */
    id: string;
}
