// This file was auto-generated by Fern from our API Definition.

import * as TransxactApi from "../../src/api/index";
import { TransxactApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("CheckoutSessionsClient", () => {
    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TransxactApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { amount: 5000, currency: "FJD" };
        const rawResponseBody = {
            id: "cs_3f9c2b1a",
            status: "pending",
            amount: 5000,
            currency: "FJD",
            hostedUrl: "https://transxact.io/c/cs_3f9c2b1a",
            metadata: { orderId: "9912" },
            expiresAt: 1717086400000,
        };

        server
            .mockEndpoint()
            .post("/v1/checkout-sessions")
            .header("idempotency-key", "a1b2c3d4-order-9912")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.checkoutSessions.create({
            "idempotency-key": "a1b2c3d4-order-9912",
            amount: 5000,
            currency: "FJD",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TransxactApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { amount: 499999, currency: "FJD" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/checkout-sessions")
            .header("idempotency-key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.checkoutSessions.create({
                "idempotency-key": "idempotencyKey",
                amount: 499999,
                currency: "FJD",
            });
        }).rejects.toThrow(TransxactApi.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TransxactApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { amount: 499999, currency: "FJD" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/checkout-sessions")
            .header("idempotency-key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.checkoutSessions.create({
                "idempotency-key": "idempotencyKey",
                amount: 499999,
                currency: "FJD",
            });
        }).rejects.toThrow(TransxactApi.UnauthorizedError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TransxactApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { amount: 499999, currency: "FJD" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/checkout-sessions")
            .header("idempotency-key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.checkoutSessions.create({
                "idempotency-key": "idempotencyKey",
                amount: 499999,
                currency: "FJD",
            });
        }).rejects.toThrow(TransxactApi.ConflictError);
    });

    test("retrieve (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TransxactApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "cs_3f9c2b1a",
            status: "pending",
            amount: 5000,
            currency: "FJD",
            hostedUrl: "https://transxact.io/c/cs_3f9c2b1a",
            metadata: { orderId: "9912" },
            expiresAt: 1717086400000,
        };

        server
            .mockEndpoint()
            .get("/v1/checkout-sessions/cs_3f9c2b1a")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.checkoutSessions.retrieve({
            id: "cs_3f9c2b1a",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("retrieve (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TransxactApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/checkout-sessions/id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.checkoutSessions.retrieve({
                id: "id",
            });
        }).rejects.toThrow(TransxactApi.NotFoundError);
    });

    test("cancel (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TransxactApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "cs_3f9c2b1a",
            status: "pending",
            amount: 5000,
            currency: "FJD",
            hostedUrl: "https://transxact.io/c/cs_3f9c2b1a",
            metadata: { orderId: "9912" },
            expiresAt: 1717086400000,
        };

        server
            .mockEndpoint()
            .post("/v1/checkout-sessions/cs_3f9c2b1a/cancel")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.checkoutSessions.cancel({
            id: "cs_3f9c2b1a",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("cancel (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TransxactApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/checkout-sessions/id/cancel")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.checkoutSessions.cancel({
                id: "id",
            });
        }).rejects.toThrow(TransxactApi.NotFoundError);
    });

    test("cancel (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TransxactApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/checkout-sessions/id/cancel")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.checkoutSessions.cancel({
                id: "id",
            });
        }).rejects.toThrow(TransxactApi.ConflictError);
    });
});
