// This file was auto-generated by Fern from our API Definition.

import * as TransxactApi from "../../src/api/index";
import { TransxactApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("TransxactApiClient", () => {
    test("postV1CheckoutSessions (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TransxactApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { amount: 5000, currency: "FJD" };
        const rawResponseBody = {
            id: "cs_3f9c2b1a",
            status: "pending",
            amount: 5000,
            currency: "FJD",
            hostedUrl: "https://checkout.transxact.com/c/cs_3f9c2b1a",
        };

        server
            .mockEndpoint()
            .post("/v1/checkout-sessions")
            .header("idempotency-key", "a1b2c3d4-order-9912")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.postV1CheckoutSessions({
            "idempotency-key": "a1b2c3d4-order-9912",
            amount: 5000,
            currency: "FJD",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("postV1CheckoutSessions (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TransxactApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { amount: 1, currency: "FJD" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/checkout-sessions")
            .header("idempotency-key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.postV1CheckoutSessions({
                "idempotency-key": "idempotencyKey",
                amount: 1,
                currency: "FJD",
            });
        }).rejects.toThrow(TransxactApi.UnauthorizedError);
    });

    test("postV1CheckoutSessions (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TransxactApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { amount: 1, currency: "FJD" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/checkout-sessions")
            .header("idempotency-key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.postV1CheckoutSessions({
                "idempotency-key": "idempotencyKey",
                amount: 1,
                currency: "FJD",
            });
        }).rejects.toThrow(TransxactApi.ConflictError);
    });

    test("getV1CheckoutSessionsId (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TransxactApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            id: "cs_3f9c2b1a",
            status: "pending",
            amount: 5000,
            currency: "FJD",
            hostedUrl: "https://checkout.transxact.com/c/cs_3f9c2b1a",
        };

        server
            .mockEndpoint()
            .get("/v1/checkout-sessions/cs_3f9c2b1a")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.getV1CheckoutSessionsId({
            id: "cs_3f9c2b1a",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getV1CheckoutSessionsId (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TransxactApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/checkout-sessions/id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.getV1CheckoutSessionsId({
                id: "id",
            });
        }).rejects.toThrow(TransxactApi.NotFoundError);
    });

    test("getV1MerchantsMe (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TransxactApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { tier: "business", mode: "test", balance: 4800 };

        server.mockEndpoint().get("/v1/merchants/me").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.getV1MerchantsMe();
        expect(response).toEqual(rawResponseBody);
    });

    test("getV1MerchantsMe (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TransxactApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server.mockEndpoint().get("/v1/merchants/me").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.getV1MerchantsMe();
        }).rejects.toThrow(TransxactApi.UnauthorizedError);
    });

    test("getV1Payouts (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TransxactApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            data: [{ id: "po_3f9c2b1a", amount: 4800, rail: "bank_transfer", createdAt: 1717000000000 }],
            hasMore: true,
        };

        server.mockEndpoint().get("/v1/payouts").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.getV1Payouts({
            starting_after: "po_3f9c2b1a",
            limit: "10",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getV1Payouts (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TransxactApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server.mockEndpoint().get("/v1/payouts").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.getV1Payouts();
        }).rejects.toThrow(TransxactApi.UnauthorizedError);
    });

    test("getV1PayoutsId (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TransxactApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { id: "po_3f9c2b1a", amount: 4800, rail: "bank_transfer", createdAt: 1717000000000 };

        server
            .mockEndpoint()
            .get("/v1/payouts/po_3f9c2b1a")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.getV1PayoutsId({
            id: "po_3f9c2b1a",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getV1PayoutsId (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TransxactApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server.mockEndpoint().get("/v1/payouts/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.getV1PayoutsId({
                id: "id",
            });
        }).rejects.toThrow(TransxactApi.NotFoundError);
    });
});
