// This file was auto-generated by Fern from our API Definition.

import * as TransxactApi from "../../src/api/index";
import { TransxactApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("MerchantsClient", () => {
    test("me (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TransxactApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { tier: "business", mode: "test", balance: 4800, payoutSchedule: "daily" };

        server.mockEndpoint().get("/v1/merchants/me").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.merchants.me();
        expect(response).toEqual({
            tier: "business",
            mode: "test",
            balance: 4800,
            payoutSchedule: "daily",
        });
    });

    test("me (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TransxactApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server.mockEndpoint().get("/v1/merchants/me").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.merchants.me();
        }).rejects.toThrow(TransxactApi.UnauthorizedError);
    });
});
