// This file was auto-generated by Fern from our API Definition.

import * as TransxactApi from "../../src/api/index";
import { TransxactApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("PayoutsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TransxactApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    id: "po_3f9c2b1a",
                    amount: 4800,
                    rail: "bank_transfer",
                    status: "pending",
                    paidAt: 1717100000000,
                    failureReason: "failureReason",
                    createdAt: 1717000000000,
                },
            ],
            hasMore: true,
        };

        server.mockEndpoint().get("/v1/payouts").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.payouts.list({
            starting_after: "po_3f9c2b1a",
            limit: "10",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TransxactApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server.mockEndpoint().get("/v1/payouts").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.payouts.list();
        }).rejects.toThrow(TransxactApi.UnauthorizedError);
    });

    test("retrieve (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TransxactApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "po_3f9c2b1a",
            amount: 4800,
            rail: "bank_transfer",
            status: "pending",
            paidAt: 1717100000000,
            failureReason: "failureReason",
            createdAt: 1717000000000,
        };

        server
            .mockEndpoint()
            .get("/v1/payouts/po_3f9c2b1a")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.payouts.retrieve({
            id: "po_3f9c2b1a",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("retrieve (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TransxactApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server.mockEndpoint().get("/v1/payouts/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.payouts.retrieve({
                id: "id",
            });
        }).rejects.toThrow(TransxactApi.NotFoundError);
    });
});
