// This file was auto-generated by Fern from our API Definition.

export const TransxactApiEnvironment = {
    Production: "https://api.transxact.io",
} as const;

export type TransxactApiEnvironment = typeof TransxactApiEnvironment.Production;
