// This file was auto-generated by Fern from our API Definition.

/** Always FJD in v1. */
export const CreateCheckoutSessionRequestCurrency = {
    Fjd: "FJD",
} as const;
export type CreateCheckoutSessionRequestCurrency =
    (typeof CreateCheckoutSessionRequestCurrency)[keyof typeof CreateCheckoutSessionRequestCurrency];
